# Site settings
title: Christopher A. Neilson
email: cneilson@princeton.edu
description: > # this means to ignore newlines until "baseurl:"
  Assistant Professor of Economics and Public Affairs at Princeton University
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: ChrisANeilson
github_username:  christopherneilson

# Build settings
markdown: kramdown

google-site-verification: google711ac5ad99c342ea.html

paginate: 3
paginate_path: "blog/page:num"

# include: ["_publications"]
plugins:
  - jekyll-sitemap
  
collections:
  work:
    output: true

defaults:
  - scope:
      path: ""
      type: work
    values:
      layout: work
